public with sharing class CRS_EditDossier {

public ID CRSRecordId {get;set;}
public ID recordId {get;set;}

Public datetime NOW {get;set;} 
public String myDate {get;set;}

public string Section_1_1Text {get;set;}
public string Section_1_2Text {get;set;} 
public string Section_2_0Text {get;set;}
public string Section_3_0Text {get;set;}
public string Section_3_1Text {get;set;}
public string Section_3_2Text {get;set;}
public string Section_4_1Text {get;set;}
public string Section_4_2Text {get;set;}
public string Section_4_3Text {get;set;}
public string Section_4_4Text {get;set;}
public string Section_4_5Text {get;set;}
public string Section_4_6Text {get;set;}
public string Section_4_7Text {get;set;}
public string Section_4_8Text {get;set;}
public string Section_5_1Text {get;set;}
public string Section_5_2Text {get;set;}
public string Section_6_1Text {get;set;}
public string Section_6_2Text {get;set;}
public string Section_6_3Text {get;set;}
public string Section_6_4Text {get;set;}
public string Section_6_5Text {get;set;}
public string Section_6_6Text {get;set;}
public string Section_7_1Text {get;set;}
public string Section_7_2Text {get;set;}
public string Section_8_0Text {get;set;}
public string Section_9_0Text {get;set;}
public string Section_10_1Text {get;set;}
public string Section_10_2Text {get;set;}
public string Section_11_0Text {get;set;}

public boolean Section_1_1Visibility {get;set;}
public boolean Section_1_2Visibility {get;set;}
public boolean Section_1_3Visibility {get;set;} 
public boolean Section_2_0Visibility {get;set;}
public boolean Section_3_0Visibility {get;set;}
public boolean Section_3_1Visibility {get;set;}
public boolean Section_3_2Visibility {get;set;}
public boolean Section_4_1Visibility {get;set;}
public boolean Section_4_2Visibility {get;set;}
public boolean Section_4_3Visibility {get;set;}
public boolean Section_4_4Visibility {get;set;}
public boolean Section_4_5Visibility {get;set;}
public boolean Section_4_6Visibility {get;set;}
public boolean Section_4_7Visibility {get;set;}
public boolean Section_4_8Visibility {get;set;}
public boolean Section_5_1Visibility {get;set;}
public boolean Section_5_2Visibility {get;set;}
public boolean Section_6_1Visibility {get;set;}
public boolean Section_6_2Visibility {get;set;}
public boolean Section_6_3Visibility {get;set;}
public boolean Section_6_4Visibility {get;set;}
public boolean Section_6_5Visibility {get;set;}
public boolean Section_6_6Visibility {get;set;} 
public boolean Section_7_1Visibility {get;set;}
public boolean Section_7_2Visibility {get;set;}
public boolean Section_8_0Visibility {get;set;}
public boolean Section_9_0Visibility {get;set;}
public boolean Section_10_1Visibility {get;set;}
public boolean Section_10_2Visibility {get;set;}
public boolean Section_11_0Visibility {get;set;}

public boolean Section_1_1required {get;set;}
public boolean Section_1_2required {get;set;}
public boolean Section_1_3required {get;set;} 
public boolean Section_2_0required {get;set;}
public boolean Section_3_0required {get;set;}
public boolean Section_3_1required {get;set;}
public boolean Section_3_2required {get;set;}
public boolean Section_4_1required {get;set;}
public boolean Section_4_2required {get;set;}
public boolean Section_4_3required {get;set;}
public boolean Section_4_4required {get;set;}
public boolean Section_4_5required {get;set;}
public boolean Section_4_6required {get;set;}
public boolean Section_4_7required {get;set;}
public boolean Section_4_8required {get;set;}
public boolean Section_5_1required {get;set;}
public boolean Section_5_2required {get;set;}
public boolean Section_6_1required {get;set;}
public boolean Section_6_2required {get;set;}
public boolean Section_6_3required {get;set;}
public boolean Section_6_4required {get;set;}
public boolean Section_6_5required {get;set;}
public boolean Section_6_6required {get;set;}   
public boolean Section_7_1required {get;set;}
public boolean Section_7_2required {get;set;}
public boolean Section_8_0required {get;set;}
public boolean Section_9_0required {get;set;}
public boolean Section_10_1required {get;set;}
public boolean Section_10_2required {get;set;}
public boolean Section_11_0required {get;set;}
    
public string Section_1_1Label {get;set;}
public string Section_1_2Label {get;set;}
public string Section_1_3Label {get;set;} 
public string Section_2_0Label {get;set;}
public string Section_3_0Label {get;set;}
public string Section_3_1Label {get;set;}
public string Section_3_2Label {get;set;}
public string Section_4_1Label {get;set;}
public string Section_4_2Label {get;set;}
public string Section_4_3Label {get;set;}
public string Section_4_4Label {get;set;}
public string Section_4_5Label {get;set;}
public string Section_4_6Label {get;set;}
public string Section_4_7Label {get;set;}
public string Section_4_8Label {get;set;}
public string Section_5_1Label {get;set;}
public string Section_5_2Label {get;set;}
public string Section_6_1Label {get;set;}
public string Section_6_2Label {get;set;}
public string Section_6_3Label {get;set;}
public string Section_6_4Label {get;set;}
public string Section_6_5Label {get;set;}
public string Section_6_6Label {get;set;}
public string Section_7_1Label {get;set;}
public string Section_7_2Label {get;set;}
public string Section_8_0Label {get;set;}
public string Section_9_0Label {get;set;}
public string Section_10_1Label {get;set;}
public string Section_10_2Label {get;set;}
public string Section_11_0Label {get;set;}

public string Section_1_1Title {get;set;}
public string Section_1_2Title {get;set;}
public string Section_1_3Title {get;set;} 
public string Section_2_0Title {get;set;}
public string Section_3_0Title {get;set;}
public string Section_3_1Title {get;set;}
public string Section_3_2Title {get;set;}
public string Section_4_1Title {get;set;}
public string Section_4_2Title {get;set;}
public string Section_4_3Title {get;set;}
public string Section_4_4Title {get;set;}
public string Section_4_5Title {get;set;}
public string Section_4_6Title {get;set;}
public string Section_4_7Title {get;set;}
public string Section_4_8Title {get;set;}
public string Section_5_1Title {get;set;}
public string Section_5_2Title {get;set;}
public string Section_6_1Title {get;set;}
public string Section_6_2Title {get;set;}
public string Section_6_3Title {get;set;}
public string Section_6_4Title {get;set;}
public string Section_6_5Title {get;set;}
public string Section_6_6Title {get;set;}
public string Section_7_1Title {get;set;}
public string Section_7_2Title {get;set;}
public string Section_8_0Title {get;set;}
public string Section_9_0Title {get;set;}
public string Section_10_1Title {get;set;}
public string Section_10_2Title {get;set;}
public string Section_11_0Title {get;set;}
public string disply {get;set;}


public CRS_Dossier__c objDossier {get;set;} 
public CRS__c objCRS {get;set;} 
public string CRSType {get;set;}
List<CRS_Dossier__c> lstDossier =new List<CRS_Dossier__c>();

    public CRS_EditDossier(ApexPages.StandardController controller) {
    NOW = system.now();
   Timezone tz = UserInfo.getTimeZone();
   String zone = tz.getId();  
   myDate = NOW.format('EEE, MMM d yyyy HH:mm:ss', zone);
   
        if( ApexPages.currentPage().getParameters().get('Id') != null){
            recordId= ApexPages.currentPage().getParameters().get('Id');
            CRSRecordId = [select Id, CRSDossierToCRS__c from CRS_Dossier__c where Id =: recordId].CRSDossierToCRS__c; 
        }
        if( ApexPages.currentPage().getParameters().get('CRSId') != null){
            CRSRecordId = ApexPages.currentPage().getParameters().get('CRSId');
            recordId = [select Id, CRSDossierToCRS__c from CRS_Dossier__c where CRSDossierToCRS__c =: CRSRecordId].Id; 
        }
        

        list<CRS__c> lstCRS = [select Id,CRS_Type_Names__c, name, Initiated_By__r.name, Date_Initiated__c, CRS_Business_Unit__r.name, CRS_Group__r.name,
                        CRS_Country_Names__c, Status__c, CRS_Product_Name__r.name, CRS_Flavor_Names__c, CRS_Brand__c,CRS_Brand__r.name,CRS_Beverage_Category__c,CRS_Beverage_Category__r.name,Date_Closed__c,
                        BBN__c, CRS_Title__c  from CRS__c where Id =: CRSRecordId];
                if(lstCRS.size() > 0){
                    objCRS = lstCRS[0];
                    CRSType = lstCRS[0].CRS_Type_Names__c;
                }
                
                lstDossier =[SELECT Id,CRSDossierToCRS__c,Section_1_1__c ,Section_1_2__c,Section_2_0__c,Section_3_0__c,
                        Section_3_1__c,Section_3_2__c, Section_4_1__c,Section_4_2__c,Section_4_3__c,Section_4_4__c,Section_4_5__c,
                        Section_4_6__c,Section_4_7__c,Section_4_8__c,Section_5_1__c,Section_5_2__c, Section_6_1__c,Section_6_2__c,
                        Section_6_3__c,Section_6_4__c, Section_6_5__c, Section_6_6__c, Section_7_1__c, Section_7_2__c,
                        Section_8_0__c,Section_9_0__c,Section_10_1__c,Section_10_2__c,Section_11_0__c from CRS_Dossier__c WHERE ID =:recordId];
                
                if(lstDossier.size() > 0){ 
                    objDossier = lstDossier[0];
                }
                
            if(CRSType != null){
                SetVisiblity(CRSType);
            }
             
    
    }
    
    public void SetVisiblity(string CRSType){
        //List<String> crsTypeList = new List<String>(); 
        system.debug(CRSType+'string value++');
        
        string[] crsTypeList = CRSType.replaceAll('; ', ';').split(';');
        //crsTypeList = CRSType.split(';');
        
        list<DossierConfiguration__c> lstDossierConf = [select Id,CRS_Type__c,Dossier_Field__c,Options__c,Field_Label__c,Tool_Tip__c from DossierConfiguration__c 
                                                where CRS_Type__c in:crsTypeList];
                                                
        for(DossierConfiguration__c obj : lstDossierConf){
            
            //section 1 
            if(obj.Dossier_Field__c == 1.1){
                Section_1_1Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_1_1Visibility = (obj.Options__c == 'Hidden' && Section_1_1Visibility != true) ? false : true;
                Section_1_1required = (obj.Options__c != 'Mandatory' && Section_1_1required != true) ? false:true;
                Section_1_1Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 1.2){
                Section_1_2Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_1_2Visibility = (obj.Options__c == 'Hidden' && Section_1_2Visibility != true) ? false : true;
                Section_1_2required = (obj.Options__c != 'Mandatory' && Section_1_2required != true) ? false:true;
                Section_1_2Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            
            //Section 2
            if(obj.Dossier_Field__c == 2.0){
                Section_2_0Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_2_0Visibility = (obj.Options__c == 'Hidden' && Section_2_0Visibility != true) ? false : true;
                Section_2_0required = (obj.Options__c != 'Mandatory' && Section_2_0required != true) ? false:true;
                Section_2_0Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            
            //section 3
            if(obj.Dossier_Field__c == 3.0){
                Section_3_0Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_3_0Visibility = (obj.Options__c == 'Hidden' && Section_3_0Visibility != true) ? false : true;
                Section_3_0required = (obj.Options__c != 'Mandatory' && Section_3_0required != true) ? false:true;
                Section_3_0Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 3.1){
                Section_3_1Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_3_1Visibility = (obj.Options__c == 'Hidden' && Section_3_1Visibility != true) ? false : true;
                Section_3_1required = (obj.Options__c != 'Mandatory' && Section_3_1required != true) ? false:true;
                Section_3_1Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 3.2){
                Section_3_2Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_3_2Visibility = (obj.Options__c == 'Hidden' && Section_3_2Visibility != true) ? false : true;
                Section_3_2required = (obj.Options__c != 'Mandatory' && Section_3_2required != true) ? false:true;
                Section_3_2Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            
            //section 4
            if(obj.Dossier_Field__c == 4.1){
                Section_4_1Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_4_1Visibility = (obj.Options__c == 'Hidden' && Section_4_1Visibility != true) ? false : true;
                Section_4_1required = (obj.Options__c != 'Mandatory' && Section_4_1required != true) ? false:true;
                Section_4_1Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 4.2){
                Section_4_2Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_4_2Visibility = (obj.Options__c == 'Hidden' && Section_4_2Visibility != true) ? false : true;
                Section_4_2required = (obj.Options__c != 'Mandatory' && Section_4_2required != true) ? false:true;
                Section_4_2Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 4.3){
                Section_4_3Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_4_3Visibility = (obj.Options__c == 'Hidden' && Section_4_3Visibility != true) ? false : true;
                Section_4_3required = (obj.Options__c != 'Mandatory' && Section_4_3required != true) ? false:true;
                Section_4_3Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 4.4){
                Section_4_4Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_4_4Visibility = (obj.Options__c == 'Hidden' && Section_4_4Visibility != true) ? false : true;
                Section_4_4required = (obj.Options__c != 'Mandatory' && Section_4_4required != true) ? false:true;
                Section_4_4Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 4.5){
                Section_4_5Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_4_5Visibility = (obj.Options__c == 'Hidden' && Section_4_5Visibility != true) ? false : true;
                Section_4_5required = (obj.Options__c != 'Mandatory' && Section_4_5required != true) ? false:true;
                Section_4_5Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 4.6){
                Section_4_6Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_4_6Visibility = (obj.Options__c == 'Hidden' && Section_4_6Visibility != true) ? false : true;
                Section_4_6required = (obj.Options__c != 'Mandatory' && Section_4_6required != true) ? false:true;
                Section_4_6Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 4.7){
                Section_4_7Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_4_7Visibility = (obj.Options__c == 'Hidden' && Section_4_7Visibility != true) ? false : true;
                Section_4_7required = (obj.Options__c != 'Mandatory' && Section_4_7required != true) ? false:true;
                Section_4_7Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 4.8){
                Section_4_8Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_4_8Visibility = (obj.Options__c == 'Hidden' && Section_4_8Visibility != true) ? false : true;
                Section_4_8required = (obj.Options__c != 'Mandatory' && Section_4_8required != true) ? false:true;
                Section_4_8Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            
            //section 5
            if(obj.Dossier_Field__c == 5.1){
                Section_5_1Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_5_1Visibility = (obj.Options__c == 'Hidden' && Section_5_1Visibility != true) ? false : true;
                Section_5_1required = (obj.Options__c != 'Mandatory' && Section_5_1required != true) ? false:true;
                Section_5_1Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 5.2){
                Section_5_2Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_5_2Visibility = (obj.Options__c == 'Hidden' && Section_5_2Visibility != true) ? false : true;
                Section_5_2required = (obj.Options__c != 'Mandatory' && Section_5_2required != true) ? false:true;
                Section_5_2Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            
            //section 6
            if(obj.Dossier_Field__c == 6.1){
                Section_6_1Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_6_1Visibility = (obj.Options__c == 'Hidden' && Section_6_1Visibility != true) ? false : true;
                Section_6_1required = (obj.Options__c != 'Mandatory' && Section_6_1required != true) ? false:true;
                Section_6_1Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 6.2){
                Section_6_2Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_6_2Visibility = (obj.Options__c == 'Hidden' && Section_6_2Visibility != true) ? false : true;
                Section_6_2required = (obj.Options__c != 'Mandatory' && Section_6_2required != true) ? false:true;
                Section_6_2Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 6.3){
                Section_6_3Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_6_3Visibility = (obj.Options__c == 'Hidden' && Section_6_3Visibility != true) ? false : true;
                Section_6_3required = (obj.Options__c != 'Mandatory' && Section_6_3required != true) ? false:true;
                Section_6_3Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 6.4){
                Section_6_4Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_6_4Visibility = (obj.Options__c == 'Hidden' && Section_6_4Visibility != true) ? false : true;
                Section_6_4required = (obj.Options__c != 'Mandatory' && Section_6_4required != true) ? false:true;
                Section_6_4Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 6.5){
                Section_6_5Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_6_5Visibility = (obj.Options__c == 'Hidden' && Section_6_5Visibility != true) ? false : true;
                Section_6_5required = (obj.Options__c != 'Mandatory' && Section_6_5required != true) ? false:true;
                Section_6_5Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 6.6){
                Section_6_6Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_6_6Visibility = (obj.Options__c == 'Hidden' && Section_6_6Visibility != true) ? false : true;
                Section_6_6required = (obj.Options__c != 'Mandatory' && Section_6_6required != true) ? false:true;
                Section_6_6Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            
            //section 7
            if(obj.Dossier_Field__c == 7.1){
                Section_7_1Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_7_1Visibility = (obj.Options__c == 'Hidden' && Section_7_1Visibility != true) ? false : true;
                Section_7_1required = (obj.Options__c != 'Mandatory' && Section_7_1required != true) ? false:true;
                Section_7_1Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 7.2){
                Section_7_2Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_7_2Visibility = (obj.Options__c == 'Hidden' && Section_7_2Visibility != true) ? false : true;
                Section_7_2required = (obj.Options__c != 'Mandatory' && Section_7_2required != true) ? false:true;
                Section_7_2Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            
            //Section 8
            if(obj.Dossier_Field__c == 8.0){
                Section_8_0Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_8_0Visibility = (obj.Options__c == 'Hidden' && Section_8_0Visibility != true) ? false : true;
                Section_8_0required = (obj.Options__c != 'Mandatory' && Section_8_0required != true) ? false:true;
                Section_8_0Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            
            //Section 9
            if(obj.Dossier_Field__c == 9.0){
                Section_9_0Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_9_0Visibility = (obj.Options__c == 'Hidden' && Section_9_0Visibility != true) ? false : true;
                Section_9_0required = (obj.Options__c != 'Mandatory' && Section_9_0required != true) ? false:true;
                Section_9_0Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            //Section 10
            if(obj.Dossier_Field__c == 10.1){
                Section_10_1Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_10_1Visibility = (obj.Options__c == 'Hidden' && Section_10_1Visibility != true) ? false : true;
                Section_10_1required = (obj.Options__c != 'Mandatory' && Section_10_1required != true) ? false:true;
                Section_10_1Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            if(obj.Dossier_Field__c == 10.2){
                Section_10_2Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_10_2Visibility = (obj.Options__c == 'Hidden' && Section_10_2Visibility != true) ? false : true;
                Section_10_2required = (obj.Options__c != 'Mandatory' && Section_10_2required != true) ? false:true;
                Section_10_2Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
            
            //Section 11
            if(obj.Dossier_Field__c == 11.0){
                Section_11_0Label = (obj.Field_Label__c != null) ? obj.Field_Label__c : null;
                Section_11_0Visibility = (obj.Options__c == 'Hidden' && Section_11_0Visibility != true) ? false : true;
                Section_11_0required = (obj.Options__c != 'Mandatory' && Section_11_0required != true) ? false:true;
                Section_11_0Title = (obj.Tool_Tip__c != null) ? obj.Tool_Tip__c : null;
            }
        }                                       
        
    }
    
    //method to save dossier
    public PageReference saveDossier(){     
        objDossier.isSubmitted__c = true;
        update objDossier;      
        
        PageReference pageRef = Page.CRS_DossierView;
        pageRef.setRedirect(true);
        pageRef.getParameters().put('CRSId',CRSRecordId); 
    
        return pageRef;
    }
    
    public PageReference saveCloseDossier(){
        objDossier.isSubmitted__c = true;
        update objDossier;
        
        PageReference pageRef = new PageReference('/'+CRSRecordId+''); 
        
        return pageRef;
    }
    
    public PageReference cancelDossier(){
        PageReference pageRef = new PageReference('/'+CRSRecordId+'');      
        return pageRef;
    }
    
    public PageReference EditDossier(){
        
        PageReference pageRef = Page.CRS_EditDossier;
        pageRef.setRedirect(true);
        pageRef.getParameters().put('Id',recordId); 
            
        return pageRef;
    }
}