/*
*
* Author,email :     Aldrin Rasdas , arasdas@coca-cola.com
* Date Create  :     Sept 20, 2013
* Description  :     Test class for GS1_Constants class
*
* REVISION HISTORY
*
* Author,email :
* Date Revised :
* Description  :
*
*
*
*/
@isTest
private class GS1_TestConstants {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Test.startTest();
        System.assert( GS1_Constants.testCoverageDummy() == 'OK');
        Test.stopTest();
    }
}